apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: parlameter-zagreb
resources:
  - update-job.yaml
images:
  - name: parlaparser-zagreb-update
    newName: rg.fr-par.scw.cloud/djnd/parlaparser-zagreb-update
    newTag: '863efa0b7db255e4b1f8a57429b262c432a9ea4a'
